apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-deployment
  namespace: eks-sample-app
  labels:
    app: rekognition-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rekognition-go
  template:
    metadata:
      labels:
        app: rekognition-go
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      serviceAccountName: eks-rekognition-access
      containers:
        - name: rekognition-go
          image: hisamitsu/rekognition-go:latest
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
